#name: Android CI/DC
#
#on: pull_request
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Set up JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#
#      - name: Run test
#        run: ./gradlew test
#
#      - name: Build Project
#        run: ./gradlew build
#
#      - name: Build apk
#        uses: actions/upload-artifacts@v1
#        with:
#          name: app
#          path: app/build/outputs/apk/debug/app-debug.apk